# -*- coding: utf-8 -*-
"""VOC분석_EDA (0716).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19b0JVXzm7D86It6cLMwsZDQzA2vXEE5Z
"""

# prompt: 위링크 인포트

import pandas as pd

# Replace with the actual URL of your Google Sheet
sheet_url = "https://docs.google.com/spreadsheets/d/1YXIxJNiv35zkQi7tdGDDQCEzERlJXtsnFbKGkBfl64c/edit?usp=sharing"

# To read the data, you need to export it as a CSV
# The URL needs to be modified to point to the export endpoint
csv_url = sheet_url.replace('/edit?usp=sharing', '/export?format=csv')

df = pd.read_csv(csv_url)

print(df.head())
print(df.info())
print(df.describe())

# prompt: 관리지사 접수일시 기준 관리지사별 몇건 계약번호 카운트로 날짜별이 아닌 월별 5월, 6월 , 7월

# Assuming your DataFrame 'df' has a column named '접수일시' and '관리지사'

# Convert '접수일시' to datetime objects
df['접수일시'] = pd.to_datetime(df['접수일시'], errors='coerce')

# Filter data for May, June, and July
df_filtered = df[df['접수일시'].dt.month.isin([5, 6, 7])].copy()

# Group by month of '접수일시' and '관리지사' and count unique '계약번호'
monthly_counts = df_filtered.groupby([df_filtered['접수일시'].dt.to_period('M'), '관리지사'])['계약번호'].count().reset_index()

# Rename the columns for clarity
monthly_counts.columns = ['월', '관리지사', '계약 건수']

# Print the result
display(monthly_counts)

# prompt: EDA코드 실행

# Perform basic EDA
print("\nBasic EDA:")
print("Shape of the DataFrame:", df.shape)
print("\nColumn names and data types:")
print(df.dtypes)

# Check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# Get unique values and their counts for categorical columns
for col in df.select_dtypes(include='object').columns:
  print(f"\nUnique values and counts for column '{col}':")
  print(df[col].value_counts())

# Calculate correlations for numerical columns (if any)
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
if len(numerical_cols) > 0:
    print("\nCorrelation Matrix:")
    print(df[numerical_cols].corr())

# Visualize data (requires matplotlib and seaborn)
# !pip install matplotlib seaborn
# import matplotlib.pyplot as plt
# import seaborn as sns

# # Example: Histogram of a numerical column (replace 'NumericalColumn' with an actual column name)
# if 'NumericalColumn' in df.columns:
#     plt.figure(figsize=(8, 6))
#     sns.histplot(df['NumericalColumn'], kde=True)
#     plt.title('Distribution of NumericalColumn')
#     plt.xlabel('NumericalColumn')
#     plt.ylabel('Frequency')
#     plt.show()

# # Example: Box plot of a numerical column by a categorical column
# # if 'NumericalColumn' in df.columns and 'CategoricalColumn' in df.columns:
# #     plt.figure(figsize=(10, 6))
# #     sns.boxplot(x='CategoricalColumn', y='NumericalColumn', data=df)
# #     plt.title('Box plot of NumericalColumn by CategoricalColumn')
# #     plt.xlabel('CategoricalColumn')
# #     plt.ylabel('NumericalColumn')
# #     plt.xticks(rotation=45)
# #     plt.show()

# prompt: 특정계약번호, 상호가 많이 발샌된 순으로

# Assuming '특정계약번호' is the column name for contract number and '상호' is the column name for company name
# Replace with the actual column names if they are different

# Combine the two columns into a new column for easier counting
df['계약번호_상호'] = df['계약번호'].astype(str) + "_" + df['상호'].astype(str)

# Count the occurrences of each combined entry
contract_company_counts = df['계약번호_상호'].value_counts()

# Sort the results in descending order
sorted_contract_company_counts = contract_company_counts.sort_values(ascending=False)

print("\n특정계약번호와 상호의 발생 빈도 (가장 많이 발생된 순서):")
sorted_contract_company_counts

# prompt: 계약번호 접수일이 2건이상만, 같은 계약번호 카운트 건수, 관리지사, 월, 데이터 다운로드

# Group by '계약번호' and count the number of '접수일시' entries
contract_reception_counts = df.groupby('계약번호')['접수일시'].count().reset_index()

# Filter for '계약번호' that have 2 or more '접수일시' entries
contracts_with_multiple_receptions = contract_reception_counts[contract_reception_counts['접수일시'] >= 2]['계약번호']

# Filter the original DataFrame to include only these contracts
df_multiple_receptions = df[df['계약번호'].isin(contracts_with_multiple_receptions)].copy()

# Count the occurrences of each '계약번호' in the filtered data
multiple_reception_counts = df_multiple_receptions['계약번호'].value_counts().reset_index()
multiple_reception_counts.columns = ['계약번호', '같은 계약번호 카운트 건수']

# Merge this count information back to the filtered DataFrame
df_multiple_receptions = pd.merge(df_multiple_receptions, multiple_reception_counts, on='계약번호', how='left')

# Convert '접수일시' to datetime objects (if not already done)
df_multiple_receptions['접수일시'] = pd.to_datetime(df_multiple_receptions['접수일시'], errors='coerce')

# Extract the month from '접수일시'
df_multiple_receptions['월'] = df_multiple_receptions['접수일시'].dt.month

# Select the desired columns
result_df = df_multiple_receptions[['계약번호', '같은 계약번호 카운트 건수', '관리지사', '월']]

# Remove duplicate rows to show unique combinations of 계약번호, 카운트, 관리지사, 월
result_df = result_df.drop_duplicates(subset=['계약번호', '같은 계약번호 카운트 건수', '관리지사', '월'])

# Display the resulting DataFrame
print("\n계약번호 접수일이 2건 이상인 데이터:")
display(result_df)

# Data download (optional, save to CSV)
result_df.to_csv('contracts_with_multiple_receptions.csv', index=False, encoding='utf-8-sig')
print("\nData saved to contracts_with_multiple_receptions.csv")

# prompt: 51750032 계약번호 발생내역 모두 보여줘

# Filter the DataFrame to show only the rows where the contract number is 51750032
contract_number_to_filter = 51750032
filtered_df = df[df['계약번호'] == contract_number_to_filter]

# Display all rows for the specified contract number
print(f"\n{contract_number_to_filter} 계약번호 발생내역:")
filtered_df

# prompt: 위 코드 접수일시 내림차순으로

# Assuming '접수일시' is the column name for the reception timestamp
# Convert the '접수일시' column to datetime objects if it's not already
df['접수일시'] = pd.to_datetime(df['접수일시'])

# Sort the DataFrame by the '접수일시' column in descending order
df_sorted_by_reception_time = df.sort_values(by='접수일시', ascending=False)

print("\n데이터를 접수일시 내림차순으로 정렬:")
print(df_sorted_by_reception_time.head()) # Display the first few rows of the sorted DataFrame

# prompt: 50907859 계약번호 발생내역 모두 보여줘

# Filter the DataFrame to show only the rows where the contract number is 50907859
contract_number_to_filter = 50907859
filtered_df = df[df['계약번호'] == contract_number_to_filter]

# Display all rows for the specified contract number
print(f"\n{contract_number_to_filter} 계약번호 발생내역:")
filtered_df

와이케이(OCT)    7.1일자 해지

# prompt: 51582169 계약번호 발생내역 모두 보여줘

# Filter the DataFrame to show only the rows where the contract number is 51582169
contract_number_to_filter = 51582169
filtered_df = df[df['계약번호'] == contract_number_to_filter]

# Display all rows for the specified contract number
print(f"\n{contract_number_to_filter} 계약번호 발생내역:")
filtered_df

뚝달리아 7.14 해지

# prompt: 50877735 계약번호 발생내역 모두 보여줘

# Filter the DataFrame to show only the rows where the contract number is 50877735
contract_number_to_filter = 50877735
filtered_df = df[df['계약번호'] == contract_number_to_filter]

# Display all rows for the specified contract number
print(f"\n{contract_number_to_filter} 계약번호 발생내역:")
filtered_df

50877735  가비엔[모두의커피]6.1일자해지



# prompt: 51916385 계약번호 발생내역 모두 보여줘

# Filter the DataFrame to show only the rows where the contract number is 51916385
contract_number_to_filter = 51916385
filtered_df = df[df['계약번호'] == contract_number_to_filter]

# Display all rows for the specified contract number
print(f"\n{contract_number_to_filter} 계약번호 발생내역:")
filtered_df

# prompt: # 설치한 라이브러리 불러오기
# # 패키지 변경 전: import pandas_profiling
# from ydata_profiling import ProfileReport # 패키지 변경 후
# # 불러온 데이터프레임에 대한 레포트 생성하기
# # 패키지 변경 전: report = df.profile_report()
# report = ProfileReport(df) # 패키지 변경 후
# # 레포트를 실행하여 확인하기
# report
# 단계별 실행 코랩에서

!pip install ydata-profiling

# 설치한 라이브러리 불러오기
# 패키지 변경 전: import pandas_profiling

from ydata_profiling import ProfileReport # 패키지 변경 후

# 불러온 데이터프레임에 대한 레포트 생성하기
# 패키지 변경 전: report = df.profile_report()

report = ProfileReport(df) # 패키지 변경 후

# 레포트를 실행하여 확인하기
report

# prompt: 일자도 월, 일

# Convert '접수일시' to datetime objects
df['접수일시_날짜'] = pd.to_datetime(df['접수일시']).dt.strftime('%Y-%m-%d')
df['접수일시_월'] = pd.to_datetime(df['접수일시']).dt.month
df['접수일시_일'] = pd.to_datetime(df['접수일시']).dt.day


# Select specific columns including the new month and day columns
selected_columns_df = df[['관리지사', '접수일시_날짜', '접수일시_월', '접수일시_일']]

# Print the selected columns
print("\nSelected Columns ('관리지사', '접수일시_날짜', '접수일시_월', '접수일시_일'):")
display(selected_columns_df.head()) # Print first few rows
display(selected_columns_df.info()) # Print info for selected columns
display(selected_columns_df.describe()) # Print descriptive statistics for selected columns (if applicable)





# Filter for '미접수' status and July
filtered_df_un 접수ed_july = df[(df['상태'] == '미접수') & (df['접수일시_월'] == 7)]

# Count the occurrences of each '계약번호' in the filtered data
contract_counts_un 접수ed_july = filtered_df_un 접수ed_july['계약번호'].value_counts()

# Sort the results in descending order
sorted_contract_counts_un 접수ed_july = contract_counts_un 접수ed_july.sort_values(ascending=False)

print("\n7월 미접수 상태의 계약번호 발생 빈도 (가장 많이 발생된 순서):")
display(sorted_contract_counts_un 접수ed_july)

# Filter the DataFrame to include only rows with '미접수', '접수', or '처리중' status
filtered_df_statuses = df[df['상태'].isin(['미접수', '접수', '처리중'])]

# Display the filtered DataFrame
print("필터링된 DataFrame (상태: 미접수, 접수, 처리중):")
display(filtered_df_statuses.head())
print("\n필터링 후 DataFrame 정보:")
display(filtered_df_statuses.info())

# Filter for '미접수', '접수', or '처리중' status
filtered_df = df[df['상태'].isin(['미접수', '접수', '처리중'])].copy()

# Convert '접수일시' to datetime objects for proper sorting
filtered_df['접수일시'] = pd.to_datetime(filtered_df['접수일시'])

# Sort within each contract number group by '접수일시' in descending order
filtered_df_sorted = filtered_df.sort_values(by=['계약번호', '접수일시'], ascending=[True, False])

# Count the occurrences of each '계약번호' in the filtered data
contract_counts = filtered_df_sorted['계약번호'].value_counts().reset_index()
contract_counts.columns = ['계약번호', '접수횟수']

# Merge the counts back to the sorted DataFrame
filtered_df_with_counts = pd.merge(filtered_df_sorted, contract_counts, on='계약번호', how='left')

# Sort the final DataFrame by '접수횟수' in descending order
final_sorted_list = filtered_df_with_counts.sort_values(by='접수횟수', ascending=False)

print("\n미접수, 접수, 처리중 상태의 계약 상세 리스트 (계약번호 기준 최근 접수일자, 발생횟수 순):")
display(final_sorted_list)

# Count the occurrences of each unique value in the '계약번호' column
contract_number_counts = df['계약번호'].value_counts()

print("\n계약번호별 발생 횟수:")
display(contract_number_counts)

# Generate the profiling report
report = ProfileReport(df)

# Display the report
display(report)

# Select the requested columns
selected_columns = ['관리지사', '계약번호', '상호', '접수일시', '등록내용', '처리내용', '처리자']
selected_df = df[selected_columns]

# Display the selected columns as a table
print("요청하신 상세 리스트:")
display(selected_df)

# Assuming contract_number_counts from the previous step is available
# If not, uncomment the following lines to calculate it again:
# contract_number_counts = df['계약번호'].value_counts()

print("\n계약번호 발생 횟수가 많은 상위 5건:")
display(contract_number_counts.head(5))

# Filter for 'VOC유형대' being '해지'
filtered_df_voc_haeji = df[df['VOC유형대'] == '해지'].copy()

# Clean and convert '월정료(VAT미포함)' to numeric, handling potential errors
filtered_df_voc_haeji['월정료(VAT미포함)_numeric'] = filtered_df_voc_haeji['월정료(VAT미포함)'].astype(str).str.replace(',', '', regex=False)
filtered_df_voc_haeji['월정료(VAT미포함)_numeric'] = pd.to_numeric(filtered_df_voc_haeji['월정료(VAT미포함)_numeric'], errors='coerce')

# Filter for '월정료(VAT미포함)_numeric' being 100000 or more
filtered_df_high_월정료 = filtered_df_voc_haeji[filtered_df_voc_haeji['월정료(VAT미포함)_numeric'] >= 100000].copy()

print("\n'VOC유형대'가 '해지'이고 '월정료(VAT미포함)'이 10만원 이상인 데이터:")
display(filtered_df_high_월정료)

# prompt: 월정료 내림차순, 접수일시 내림차순, 월정료 천단위 콤마, 뒤 불필요 0 제외, 접수일시 내림차순 최근날짜순, 계약번호도 불필요 0 제외

# Clean and convert '월정료(VAT미포함)' to numeric, handling potential errors
df['월정료(VAT미포함)_numeric'] = df['월정료(VAT미포함)'].astype(str).str.replace(',', '', regex=False)
df['월정료(VAT미포함)_numeric'] = pd.to_numeric(df['월정료(VAT미포함)_numeric'], errors='coerce')

# Convert '접수일시' to datetime objects for sorting
df['접수일시'] = pd.to_datetime(df['접수일시'])

# Sort by '월정료(VAT미포함)_numeric' descending, then by '접수일시' descending
sorted_df = df.sort_values(by=['월정료(VAT미포함)_numeric', '접수일시'], ascending=[False, False]).copy()

# Format '월정료(VAT미포함)_numeric' to display with comma as thousand separator and remove trailing zeros
# Handle potential NaNs from conversion
sorted_df['월정료(VAT미포함)_formatted'] = sorted_df['월정료(VAT미포함)_numeric'].apply(
    lambda x: f"{x:,.0f}" if pd.notnull(x) else ''
)

# Remove unnecessary trailing zeros from '계약번호' by converting to string and removing '.0' if present
sorted_df['계약번호_formatted'] = sorted_df['계약번호'].astype(str).str.replace('\.0$', '', regex=True)

# Display the sorted DataFrame with formatted columns
print("\n월정료 내림차순, 접수일시 내림차순으로 정렬된 데이터 (월정료 천단위 콤마, 계약번호 불필요 0 제외):")
display(sorted_df[['관리지사', '계약번호_formatted', '상호', '접수일시', '등록내용', '처리내용', '처리자', '월정료(VAT미포함)_formatted']].head())
display(sorted_df[['관리지사', '계약번호_formatted', '상호', '접수일시', '등록내용', '처리내용', '처리자', '월정료(VAT미포함)_formatted']])

# Filter the DataFrame for the month of July using the '접수일시_월' column
july_df = df[df['접수일시_월'] == 7]

print("\n7월 데이터:")
display(july_df.head())
display(july_df.info())

# ✅ 나눔폰트 설치
!apt-get -qq install -y fonts-nanum

# ✅ matplotlib 캐시 초기화
import matplotlib.font_manager as fm
import matplotlib as mpl
import matplotlib.pyplot as plt

# ✅ 설치된 나눔 폰트 경로 확인 및 등록
font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

for font_file in font_files:
    fm.fontManager.addfont(font_file)

# ✅ 나눔고딕을 matplotlib의 기본 폰트로 설정
plt.rcParams['font.family'] = 'NanumGothic'
mpl.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지

# ✅ 한글 폰트 설치
!apt-get -qq install -y fonts-nanum > /dev/null

# ✅ 설치된 나눔폰트 자동 등록 및 설정
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl

# ✅ 나눔폰트 경로 탐색
font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

# ✅ 등록 및 적용
for font_file in font_files:
    fm.fontManager.addfont(font_file)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

print("✅ 한글 폰트(NanumGothic) 설정 완료!")



plt.figure(figsize=(6, 4))
plt.plot([1, 2, 3], [10, 30, 20], marker='o')
plt.title("한글 제목: 테스트 그래프")
plt.xlabel("X축 값")
plt.ylabel("Y축 값")
plt.grid(True)
plt.tight_layout()
plt.show()



# ✅ 한글 폰트 설치
!apt-get -qq install -y fonts-nanum > /dev/null

# ✅ 설치된 나눔폰트 자동 등록 및 설정
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl

# ✅ 나눔폰트 경로 탐색
font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

# ✅ 등록 및 적용
for font_file in font_files:
    fm.fontManager.addfont(font_file)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

print("✅ 한글 폰트(NanumGothic) 설정 완료!")


# Create a bar plot
plt.figure(figsize=(12, 6))
sns.barplot(data=monthly_counts, x='월', y='계약 건수', hue='관리지사')

# Add titles and labels
plt.title('월별 관리지사별 계약 건수')
plt.xlabel('월')
plt.ylabel('계약 건수')
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
plt.legend(title='관리지사', bbox_to_anchor=(1.05, 1), loc='upper left') # Move legend outside the plot
plt.tight_layout() # Adjust layout to prevent labels overlapping

# Show the plot
plt.show()

# prompt: VOC유형대 "해지"만 지사, 월별 시각화, 막대그래프에 건수 표시

import matplotlib.pyplot as plt
import seaborn as sns

# Filter for 'VOC유형대' being '해지'
df_haeji = df[df['VOC유형대'] == '해지'].copy()

# Ensure '접수일시' is in datetime format
df_haeji['접수일시'] = pd.to_datetime(df_haeji['접수일시'], errors='coerce')

# Extract the month and format it
df_haeji['월'] = df_haeji['접수일시'].dt.to_period('M').astype(str)

# Group by '관리지사' and '월' and count occurrences
haeji_counts = df_haeji.groupby(['관리지사', '월']).size().reset_index(name='해지 건수')

# Sort by month
haeji_counts = haeji_counts.sort_values(by='월')

# Create a bar plot
plt.figure(figsize=(14, 7))
ax = sns.barplot(data=haeji_counts, x='월', y='해지 건수', hue='관리지사')

# Add count labels on top of the bars
for container in ax.containers:
    ax.bar_label(container, fmt='%d')

# Add titles and labels
plt.title('월별 관리지사별 해지 건수')
plt.xlabel('월')
plt.ylabel('해지 건수')
plt.xticks(rotation=45, ha='right')
plt.legend(title='관리지사', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()

# Show the plot
plt.show()

# prompt: 7월 계약번호 기준 2번이상 카운트 시설 지사별 건수 막대그래프표시

# Convert '접수일시' to datetime objects and extract the month
df['접수일시'] = pd.to_datetime(df['접수일시'], errors='coerce')
df['접수일시_월'] = df['접수일시'].dt.month

# Filter data for July
july_df = df[df['접수일시_월'] == 7].copy()

# Group by '계약번호' and count occurrences
july_contract_counts = july_df.groupby('계약번호').size().reset_index(name='접수횟수')

# Filter for contract numbers that appeared 2 or more times in July
july_repeated_contracts = july_contract_counts[july_contract_counts['접수횟수'] >= 2]

# Merge this back with the original July data to get the branch information
july_repeated_contracts_df = pd.merge(july_repeated_contracts, july_df, on='계약번호', how='left')

# Get the unique contract numbers that appeared 2 or more times
unique_repeated_contracts = july_repeated_contracts_df['계약번호'].unique()

# Filter the original July DataFrame to keep only the rows corresponding to these unique contract numbers
july_filtered_for_repeated = july_df[july_df['계약번호'].isin(unique_repeated_contracts)].copy()

# Count the occurrences of these repeated contracts by '관리지사'
branch_repeated_counts = july_filtered_for_repeated.groupby('관리지사')['계약번호'].nunique().reset_index(name='2회이상_계약_건수')

print("\n7월 계약번호 기준 2번 이상 발생한 시설의 지사별 건수:")
display(branch_repeated_counts)

# Create a bar plot
plt.figure(figsize=(12, 6))
ax = sns.barplot(data=branch_repeated_counts, x='관리지사', y='2회이상_계약_건수')

# Add count labels on top of the bars
for container in ax.containers:
    ax.bar_label(container, fmt='%d')

# Add titles and labels
plt.title('7월 2회 이상 접수된 시설의 지사별 건수')
plt.xlabel('관리지사')
plt.ylabel('2회 이상 접수된 시설 수')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

# Show the plot
plt.show()

# prompt: 위 막대그래프 중앙지사 16건 상세리스트

# Filter data for July and "중앙지사"
joongang_july_df = df[(df['접수일시_월'] == 7) & (df['관리지사'] == '중앙지사')].copy()

# Count the unique contract numbers for "중앙지사" in July to verify the count
unique_contracts_count_joongang_july = joongang_july_df['계약번호'].nunique()
print(f"\n7월 중앙지사에서 발생한 고유 계약번호 수: {unique_contracts_count_joongang_july} 건")

# If you want to see the list of unique contract numbers for "중앙지사" in July:
# print("\n7월 중앙지사 고유 계약번호 목록:")
# display(joongang_july_contracts)



# ✅ 한글 폰트 설치
!apt-get -qq install -y fonts-nanum > /dev/null

# ✅ 설치된 나눔폰트 자동 등록 및 설정
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl

# ✅ 나눔폰트 경로 탐색
font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = fm.findSystemFonts(fontpaths=font_dirs)

# ✅ 등록 및 적용
for font_file in font_files:
    fm.fontManager.addfont(font_file)

plt.rc('font', family='NanumGothic')
mpl.rcParams['axes.unicode_minus'] = False

print("✅ 한글 폰트(NanumGothic) 설정 완료!")

# Convert '접수일시' to datetime objects for proper sorting
df['접수일시'] = pd.to_datetime(df['접수일시'], errors='coerce')

# Get unique values in the '관리지사' column
unique_branches = df['관리지사'].unique()

# Iterate through each unique branch and display a sorted table
for branch in unique_branches:
    print(f"\n--- 관리지사: {branch} ---")

    # Filter data for the current branch
    branch_df = df[df['관리지사'] == branch].copy()

    # Sort by '접수일시' in descending order
    sorted_branch_df = branch_df.sort_values(by='접수일시', ascending=False)

    # Display the selected columns as a table
    display(sorted_branch_df[['관리지사', '계약번호', '접수일시']])

# Combine '계약번호' and '상호' for counting
# Handle potential NaN values in '상호' by converting to string
df['계약번호_상호'] = df['계약번호'].astype(str) + ' - ' + df['상호'].astype(str)

# Count the occurrences of each combined entry
contract_biz_counts = df['계약번호_상호'].value_counts().reset_index()

# Rename columns for clarity
contract_biz_counts.columns = ['계약번호_상호', '발생횟수']

# Sort by occurrence count in descending order
contract_biz_counts = contract_biz_counts.sort_values(by='발생횟수', ascending=False)

print("\n계약번호와 상호 조합별 발생 횟수 (가장 많이 발생된 순서):")
display(contract_biz_counts)

# prompt: 51632246 계약번호 발생내역 상세표

contract_number_to_filter = 51632246
filtered_df = df[df['계약번호'] == contract_number_to_filter]

# Display all rows for the specified contract number
print(f"\n{contract_number_to_filter} 계약번호 발생내역 상세표:")
display(filtered_df)











# Filter for rows where '관리지사' and '처리자' are not null
filtered_df_present_cols = df[df['관리지사'].notnull() & df['처리자'].notnull()].copy()

print("\n'관리지사'와 '처리자' 정보가 있는 데이터:")
display(filtered_df_present_cols.head())
display(filtered_df_present_cols.info())

# prompt: 7월 계약번호 기준 2번이상 카운트 시설 지사별 건수 막대그래프표시결과 중앙지사 상세리스트월정료도 표시

# Filter the DataFrame containing repeated contracts in July for '중앙지사'
joongang_july_repeated_contracts_df = july_repeated_contracts_df[july_repeated_contracts_df['관리지사'] == '중앙지사'].copy()

# Merge with the original DataFrame to include the formatted 월정료 column
joongang_july_repeated_contracts_df = pd.merge(
    joongang_july_repeated_contracts_df,
    df[['계약번호', '월정료(VAT미포함)']],
    on='계약번호',
    how='left'
)

print("\n7월 중앙지사에서 2회 이상 발생한 계약 상세 리스트:")
# Display relevant columns for the detailed list, including 월정료
display(joongang_july_repeated_contracts_df[['관리지사', '계약번호', '상호', '접수일시', '등록내용', '처리내용', '처리자', '접수횟수_x', '월정료(VAT미포함)_x']])